# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name : "React Setup"
    init: echo 'Front End Setup' # runs during prebuild
    command: echo 'start script' && cd frontend_react && npm i && npm start
    
  - name : "Sanity Setup"
    init: echo 'Back End Setup' # runs during prebuild
    command: echo 'start script' && cd backend-sanity && npm i && sanity start
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3333
    onOpen: open-preview
