# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# BEFORE -> INIT -> COMMAND 
# before: Use this for tasks that need to run before init and before
#command. For example, customize the terminal or install global project dependencies.
# init: Use this for heavy-lifting tasks such as downloading dependencies or compiling source code.
# command: Use this to start your database or development server
tasks:
  - name : "React Setup"
    init: cd frontend_react && npm install  
    command: npm start
    
  - name : "Sanity Setup"
    init: cd backend-sanity && npm i && npm i @sanity/cli
    command: npm start
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3333
    onOpen: open-preview
